/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-05-28 11:40:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.MarksheetListCtl;
import com.sunilos.p4.ctl.BaseCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.ServletUtility;
import com.sunilos.p4.bean.MarksheetBean;
import java.util.List;
import java.util.Iterator;
import com.sunilos.p4.ctl.BaseCtl;

public final class MarksheetListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/ListFooter.jsp", Long.valueOf(1779965136000L));
    _jspx_dependants.put("/WEB-INF/ors-tag-lib.tld", Long.valueOf(1779965136000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.MarksheetListCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.BaseCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
    _jspx_imports_classes.add("com.sunilos.p4.bean.MarksheetBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    int pageNo   = ServletUtility.getPageNo(request);
    int pageSize = ServletUtility.getPageSize(request);
    int index    = ((pageNo - 1) * pageSize) + 1;
    List list    = ServletUtility.getList(request);
    Iterator<MarksheetBean> it = list.iterator();
    String _err  = ServletUtility.getErrorMessage(request);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid px-4 py-4\" style=\"max-width:1050px;\">\r\n");
      out.write("  <div class=\"card border-0 shadow-sm rounded-4 overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card-header text-white border-0 py-3 px-4 d-flex justify-content-between align-items-center\"\r\n");
      out.write("         style=\"background:linear-gradient(135deg,#0d2137 0%,#1565c0 100%);\">\r\n");
      out.write("      <h5 class=\"mb-0 fw-bold\"><i class=\"bi bi-file-earmark-text-fill me-2\"></i> ");
      if (_jspx_meth_ors_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</h5>\r\n");
      out.write("      <a href=\"MarksheetCtl\" class=\"btn btn-sm btn-light text-primary fw-semibold\">\r\n");
      out.write("        <i class=\"bi bi-plus-circle me-1\"></i> ");
      if (_jspx_meth_ors_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("      <input type=\"hidden\" name=\"pageNo\"   value=\"");
      out.print(pageNo);
      out.write("\">\r\n");
      out.write("      <input type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"p-3 bg-light border-bottom d-flex flex-wrap gap-2 align-items-center\">\r\n");
      out.write("        <input type=\"text\" name=\"name\" class=\"form-control form-control-sm\" style=\"max-width:180px;\"\r\n");
      out.write("               placeholder=\"Student Name\" value=\"");
      out.print(ServletUtility.getParameter("name", request));
      out.write("\">\r\n");
      out.write("        <input type=\"text\" name=\"rollNo\" class=\"form-control form-control-sm\" style=\"max-width:160px;\"\r\n");
      out.write("               placeholder=\"Roll No\" value=\"");
      out.print(ServletUtility.getParameter("rollNo", request));
      out.write("\">\r\n");
      out.write("        <button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_SEARCH);
      out.write("\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("          <i class=\"bi bi-search me-1\"></i> ");
      if (_jspx_meth_ors_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("        <button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_DELETE);
      out.write("\" class=\"btn btn-danger btn-sm ms-auto\"\r\n");
      out.write("                onclick=\"return confirm('Delete selected marksheets?')\">\r\n");
      out.write("          <i class=\"bi bi-trash me-1\"></i> ");
      if (_jspx_meth_ors_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
 if(_err != null && !_err.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger py-2 mx-3 mt-3\"><i class=\"bi bi-exclamation-triangle-fill me-2\"></i>");
      out.print(_err);
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"table-responsive\">\r\n");
      out.write("        <table class=\"table table-hover align-middle mb-0\">\r\n");
      out.write("          <thead class=\"table-light\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th width=\"40\"><input type=\"checkbox\" onclick=\"document.querySelectorAll('input[name=ids]').forEach(c=>c.checked=this.checked)\"></th>\r\n");
      out.write("              <th>#</th>\r\n");
      out.write("              <th>ID</th>\r\n");
      out.write("              <th>");
      if (_jspx_meth_ors_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("              <th>");
      if (_jspx_meth_ors_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("              <th class=\"text-center\">");
      if (_jspx_meth_ors_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("              <th class=\"text-center\">");
      if (_jspx_meth_ors_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("              <th class=\"text-center\">");
      if (_jspx_meth_ors_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("              <th>");
      if (_jspx_meth_ors_005fmessage_005f9(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody>\r\n");
      out.write("            ");
 while(it.hasNext()) { MarksheetBean bean = it.next(); 
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td><input type=\"checkbox\" name=\"ids\" value=\"");
      out.print(bean.getId());
      out.write("\"></td>\r\n");
      out.write("              <td class=\"text-muted small\">");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("              <td class=\"text-muted small\">");
      out.print(bean.getId());
      out.write("</td>\r\n");
      out.write("              <td class=\"fw-semibold\">");
      out.print(bean.getRollNo());
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print(bean.getName());
      out.write("</td>\r\n");
      out.write("              <td class=\"text-center\">");
      out.print(bean.getPhysics());
      out.write("</td>\r\n");
      out.write("              <td class=\"text-center\">");
      out.print(bean.getChemistry());
      out.write("</td>\r\n");
      out.write("              <td class=\"text-center\">");
      out.print(bean.getMaths());
      out.write("</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <a href=\"MarksheetCtl?id=");
      out.print(bean.getId());
      out.write("\" class=\"btn btn-sm btn-outline-primary\">\r\n");
      out.write("                  <i class=\"bi bi-pencil\"></i> ");
      if (_jspx_meth_ors_005fmessage_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"p-3 border-top\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<div class=\"d-flex justify-content-center align-items-center gap-2\">\r\n");
      out.write("  <button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_PREVIOUS);
      out.write("\"\r\n");
      out.write("          class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("    <i class=\"bi bi-chevron-left\"></i> Previous\r\n");
      out.write("  </button>\r\n");
      out.write("  <button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_NEXT);
      out.write("\"\r\n");
      out.write("          class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("    Next <i class=\"bi bi-chevron-right\"></i>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ors_005fmessage_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f0 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f0.setParent(null);
      // /jsp/MarksheetListView.jsp(24,81) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f0.setKey("marksheet.list.title");
      int _jspx_eval_ors_005fmessage_005f0 = _jspx_th_ors_005fmessage_005f0.doStartTag();
      if (_jspx_th_ors_005fmessage_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f1 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f1.setParent(null);
      // /jsp/MarksheetListView.jsp(26,47) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f1.setKey("marksheet.add");
      int _jspx_eval_ors_005fmessage_005f1 = _jspx_th_ors_005fmessage_005f1.doStartTag();
      if (_jspx_th_ors_005fmessage_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f2 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f2.setParent(null);
      // /jsp/MarksheetListView.jsp(40,44) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f2.setKey("button.search");
      int _jspx_eval_ors_005fmessage_005f2 = _jspx_th_ors_005fmessage_005f2.doStartTag();
      if (_jspx_th_ors_005fmessage_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f3 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f3.setParent(null);
      // /jsp/MarksheetListView.jsp(44,43) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f3.setKey("button.delete.selected");
      int _jspx_eval_ors_005fmessage_005f3 = _jspx_th_ors_005fmessage_005f3.doStartTag();
      if (_jspx_th_ors_005fmessage_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f4 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f4.setParent(null);
      // /jsp/MarksheetListView.jsp(59,18) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f4.setKey("marksheet.rollno");
      int _jspx_eval_ors_005fmessage_005f4 = _jspx_th_ors_005fmessage_005f4.doStartTag();
      if (_jspx_th_ors_005fmessage_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f5 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f5.setParent(null);
      // /jsp/MarksheetListView.jsp(60,18) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f5.setKey("marksheet.student.name");
      int _jspx_eval_ors_005fmessage_005f5 = _jspx_th_ors_005fmessage_005f5.doStartTag();
      if (_jspx_th_ors_005fmessage_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f6 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f6.setParent(null);
      // /jsp/MarksheetListView.jsp(61,38) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f6.setKey("marksheet.physics");
      int _jspx_eval_ors_005fmessage_005f6 = _jspx_th_ors_005fmessage_005f6.doStartTag();
      if (_jspx_th_ors_005fmessage_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f7 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f7.setParent(null);
      // /jsp/MarksheetListView.jsp(62,38) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f7.setKey("marksheet.chemistry");
      int _jspx_eval_ors_005fmessage_005f7 = _jspx_th_ors_005fmessage_005f7.doStartTag();
      if (_jspx_th_ors_005fmessage_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f8 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f8.setParent(null);
      // /jsp/MarksheetListView.jsp(63,38) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f8.setKey("marksheet.maths");
      int _jspx_eval_ors_005fmessage_005f8 = _jspx_th_ors_005fmessage_005f8.doStartTag();
      if (_jspx_th_ors_005fmessage_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f9 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f9.setParent(null);
      // /jsp/MarksheetListView.jsp(64,18) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f9.setKey("label.action");
      int _jspx_eval_ors_005fmessage_005f9 = _jspx_th_ors_005fmessage_005f9.doStartTag();
      if (_jspx_th_ors_005fmessage_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f10(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f10 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f10.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f10.setParent(null);
      // /jsp/MarksheetListView.jsp(80,47) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f10.setKey("button.edit");
      int _jspx_eval_ors_005fmessage_005f10 = _jspx_th_ors_005fmessage_005f10.doStartTag();
      if (_jspx_th_ors_005fmessage_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f10);
    }
    return false;
  }
}
