/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-05-30 06:33:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.ForgetPasswordCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.DataUtility;
import com.sunilos.p4.util.ServletUtility;

public final class ForgetPasswordView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ForgetPasswordCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.util.DataUtility");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.sunilos.p4.bean.UserBean bean = null;
      bean = (com.sunilos.p4.bean.UserBean) _jspx_page_context.getAttribute("bean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new com.sunilos.p4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

    String _suc = ServletUtility.getSuccessMessage(request);
    String _err = ServletUtility.getErrorMessage(request);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\" style=\"max-width:520px;\">\r\n");
      out.write("  <div class=\"card border-0 shadow-sm rounded-4 overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card-header text-white border-0 py-4 px-4 text-center\"\r\n");
      out.write("         style=\"background:linear-gradient(135deg,#0d2137 0%,#1565c0 100%);\">\r\n");
      out.write("      <div class=\"d-flex justify-content-center mb-3\">\r\n");
      out.write("        <div class=\"rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("             style=\"width:60px;height:60px;background:rgba(255,255,255,0.18);font-size:1.6rem;border:2px solid rgba(255,255,255,0.3);\">\r\n");
      out.write("          <i class=\"bi bi-question-circle-fill\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h5 class=\"mb-1 fw-bold\">Forgot Password?</h5>\r\n");
      out.write("      <p class=\"mb-0 opacity-75 small\">Enter your email and we'll send your password.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card-body px-4 py-4\">\r\n");
      out.write("\r\n");
      out.write("      ");
 if(_suc != null && !_suc.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-success py-2\"><i class=\"bi bi-check-circle-fill me-2\"></i>");
      out.print(_suc);
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      ");
 if(_err != null && !_err.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger py-2\"><i class=\"bi bi-exclamation-triangle-fill me-2\"></i>");
      out.print(_err);
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <form action=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("          <label class=\"form-label fw-semibold\">Email / Login ID <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          <input type=\"text\" name=\"login\" class=\"form-control form-control-lg\"\r\n");
      out.write("                 placeholder=\"Enter your registered email\"\r\n");
      out.write("                 value=\"");
      out.print(ServletUtility.getParameter("login", request));
      out.write("\">\r\n");
      out.write("          <div class=\"text-danger small mt-1\">");
      out.print(ServletUtility.getErrorMessage("login", request));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" name=\"operation\" value=\"");
      out.print(ForgetPasswordCtl.OP_GO);
      out.write("\"\r\n");
      out.write("                class=\"btn btn-primary btn-lg w-100\">\r\n");
      out.write("          <i class=\"bi bi-send me-2\"></i> Send Password\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text-center mt-3\">\r\n");
      out.write("          <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\" class=\"text-secondary small text-decoration-none\">\r\n");
      out.write("            <i class=\"bi bi-arrow-left me-1\"></i> Back to Login\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
